import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  typescriptSidebar: [{type: 'autogenerated', dirName: 'typescript'}],

  swiftSidebar: [{type: 'autogenerated', dirName: 'swift'}],

  kotlinSidebar: [{type: 'autogenerated', dirName: 'kotlin'}],

  rustSidebar: [{type: 'autogenerated', dirName: 'rust'}],

  otherSidebar: [{type: 'autogenerated', dirName: 'others'}],
};

export default sidebars;
