import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  typescriptSidebar: [{type: 'autogenerated', dirName: 'typescript'}],

  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],

  kotlinSidebar: [{type: 'autogenerated', dirName: 'kotlin'}],

  swiftSidebar: [{type: 'autogenerated', dirName: 'swift'}],

  golangSidebar: [{type: 'autogenerated', dirName: 'go'}],  

  rustSidebar: [{type: 'autogenerated', dirName: 'rust'}],
};

export default sidebars;
