import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],

  golangSidebar: [{type: 'autogenerated', dirName: 'go'}],

  rustSidebar: [{type: 'autogenerated', dirName: 'rust'}],

  kotlinSidebar: [{type: 'autogenerated', dirName: 'kotlin'}],

  swiftSidebar: [{type: 'autogenerated', dirName: 'swift'}],
};

export default sidebars;
