import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  basicSidebar: [{type: 'autogenerated', dirName: 'basic'}],

  advancedSidebar: [{type: 'autogenerated', dirName: 'advanced'}],

  frameworksSidebar: [{type: 'autogenerated', dirName: 'frameworks'}],

  apiSidebar: [{type: 'autogenerated', dirName: 'for-api'}],

  aiSidebar: [{type: 'autogenerated', dirName: 'for-ai'}],
};

export default sidebars;
